language: elixir

matrix:
  include:
    - otp_release: 20.0
      elixir: 1.5.0
    - otp_release: 19.3
      elixir: 1.5.0
    - otp_release: 18.3
      elixir: 1.5.0

before_script:
  - mix deps.get --only test

script:
  - mix test

after_script:
  - MIX_ENV=test mix coveralls.travis
