language: elixir

matrix:
  include:
    - elixir: 1.5.3
      otp_release: 20.1
    - elixir: 1.5.3
      otp_release: 19.3
    - elixir: 1.5.3
      otp_release: 18.3

sudo: false

before_script:
  - kerl list installations

script:
  - mix test

after_script:
  - MIX_ENV=test mix coveralls.travis
  - MIX_ENV=docs mix inch.report
